  <?php echo $this->flashSession->output(); 
 
  $username='';
  $password='';
  $rememberMe='';
 
  if($this->cookies->has("username") && $this->cookies->has("password") )
  {
      $username=$this->cookies->get("username");
      $password=$this->cookies->get("password");
      $rememberMe='checked';
  }
?>
<link rel="stylesheet" href="css/style.css">

  <div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->
    <h2 class="active"> Sign In </h2>

    <!-- Icon -->
    <div class="fadeIn first">
      <img src="http://danielzawadzki.com/codepen/01/icon.svg" id="icon" alt="User Icon" />
    </div>

    <!-- Login Form -->
    <form action="" method="post">
      <input type="text" id="login" class="fadeIn second" name="email" placeholder="Enter Email" value="<?php if(isset($username))echo $username; ?>" required>
      <input style="-webkit-text-security:square;" type="text" id="password" class="fadeIn third" name="password" placeholder="Password" value="<?php if(isset($password))echo $password; ?>" required>
      <div class="form-check">
      <input type="checkbox" name="rememberMe" class="form-check-input fadeIn third" id="rememberMe" value="1" <?php echo $rememberMe;?>>
      <label class="form-check-label" for="rememberMe">Remember me</label>
    </div>
      <input type="submit" class="fadeIn fourth" value="Log In">
    </form>

    <!-- Remind Passowrd -->
    <div id="formFooter">
      <a href="<?php echo $this->url->getBaseUri(); ?>" class="underlineHover">Back</a>
    </div>

  </div>
</div>
